### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by siglun**
This is a pull request. Those requests are  git's method of making reviews. In a pull request someone proposes a modification or revision in a branch of a project. The request is sent to reviewers whose job it is to ensure that the revision improves the project. I usually send pull request to fellow project workers. In this case I feel that the revision I propose is more significant then usual, and it is also less technical (or less artistic).

This branch is called `add-license-1`. The revision I propose is that we add a LICENSE to the `SKS_tei` data source project. It is a standard CC0 license. The reason for this is that people has asked (recently someone in New Mexico asked wondered about it).

Also I want  all you and KB to be aware that

1. the SKS_tei data is in a public github project. It has been so since September 2017. I have informed anyone that I believed could have opinions about this.
2. if you accept this pull request the source will be available on the same terms as the SKS content in text service. Note the formulation: _"Materialet er dedikeret til public domain. Man kan kopiere, ændre, distribuere og fremføre værket, også til kommercielle formål, uden at bede om tilladelse. Husk dog altid at kreditere ophavsmanden."_ (https://tekster.kb.dk/sks)

If you so wish, we can merge the branch `add-license-1` into the `master`. Then CC0 will become the license for `SKS_tei` data source. Alternatively, we can close the pull request, and make the data in this project `private`

### CODE REVIEW

**Comment by tokee** [comment]
I am (of course) of the opinion that there should be a license and that the license should indeed be CC0. But I am not a lawyer.

Only minor thing I have to add is that crediting the author is optional under CC0 as well as Public Domain, så maybe it should be "_Det anses for god skik at kreditere ophavsmanden_", adding who the ophavsmand is in this scenario. I presume it is Søren, but I am not sure.

**Comment by boks-kb-dk** [comment]
It is totally correct according to KB’s strategy that we publicize license conditions whenever we publicize KB’s collections.  So Sigge is right, we need a license file.

In the SKS case it also correct that it’s a CC0 license.

The wording of the KB’s CC0 license description on KB’s sites has been extensively discussed internally amongst KB’s legal team. 

Unfortunately, (as always) they have produced only a Danish text, which is the following:

> Ophavsret
> Materialet er dedikeret til public domain. Du kan kopiere, ændre, distribuere og fremføre værket, også til kommercielle formål, uden at bede om tilladelse. Husk dog altid at kreditere ophavsmanden.
> [Læs CC0-erklæringen](https://creativecommons.org/publicdomain/zero/1.0/deed.da)
> 

It can be seen, for instance, on the new SKS pages in tekster.kb.dk:  https://tekster.kb.dk/text/sks-pcs-txt-root    (click the ‘Info’ button)

Note that our Danish text includes ”Husk dog altid at kreditere ophavsmanden”, which is exactly what Toke suggests. 

I would like that to be added to the CC0 text in Github.  We need KB’s legal team to approve/adjust the text in Github.  They (Louise A.) are already on it.

**Comment by tokee** [comment]
> Note that our Danish text includes ”Husk dog altid at kreditere ophavsmanden”, which is exactly what Toke suggests.

Sorry, but it is not. My point is the opposite: CC0 is the only CC-license that _does not_ require attribution. At least not from a legal point of view. I was asking for

1. A wording that is more explicit about it being a norm rather than a rule
2. Who (and how) to credit

References:
- https://wiki.creativecommons.org/wiki/CC0_FAQ#Does_CC0_require_others_who_use_my_work_to_give_me_attribution.3F
- https://wiki.creativecommons.org/wiki/CC0_FAQ#Can_I_control_how_my_work_is_being_used_once_I_publish_it_using_CC0.3F

**Comment by siglun** [comment]
Legalese is not any of my strengths. Louise said that attribution is necessary according to Danish law. But @tokee is (obviously) correct when it comes to CC0. (I also noted CC's wording; "Unlike our licenses, there are no conditions contained in CC0." Hence, CC0 is *not* a CC license.)

**Comment by siglun** [comment]
And you cannot quote something in an academic context without a proper reference....

**Comment by siglun** [comment]
After discussions with Lousie, I've merged this.

**Comment by boks-kb-dk** [comment]
Fine.  Yes, Louise must decide.

**Comment by boks-kb-dk** [comment]
It is totally correct according to KB’s strategy that we publicize license conditions whenever we publicize KB’s collections.  So Sigge is right, we need a license file.

In the SKS case it also correct that it’s a CC0 license.

The wording of the KB’s CC0 license description on KB’s sites has been extensively discussed internally amongst KB’s legal team.

Unfortunately, (as always) they have produced only a Danish text, which is the following:
Ophavsret
Materialet er dedikeret til public domain. Du kan kopiere, ændre, distribuere og fremføre værket, også til kommercielle formål, uden at bede om tilladelse. Husk dog altid at kreditere ophavsmanden.
Læs CC0-erklæringen<https://creativecommons.org/publicdomain/zero/1.0/deed.da>

It can be seen, for instance, on the new SKS pages in tekster.kb.dk:  https://tekster.kb.dk/text/sks-pcs-txt-root    (click the ‘Info’ button)

Note that our Danish text includes ”Husk dog altid at kreditere ophavsmanden”, which is exactly what Toke suggests.

I would like that to be added to the CC0 text in Github.  We need KB’s legal team to approve/adjust the text in Github.  They (Louise A.) are already on it.

Best
Bo

DKU
KB
Tel:  2043 7558

**Pull request merged**
